### ISSUE TITLE
no link to repository in package.json

### ISSUE THREAD

**Issue by Steve-Mcl** [jsccjj/node-red-contrib-f2flowchart#1]
hi, 

your `package.json` is missing 

```json
  "repository": {
    "type": "git",
    "url": "https://github.com/jsccjj/node-red-contrib-f2flowchart"
  },
```

meaning users cannot easily locate the repository from npm or the flows library

Would you consider adding this?

**Comment by jscc-me** [comment]
@Steve-Mcl    Thank you for bringing this up. I just made the modification. Would you consider close this issue?

**Comment by Steve-Mcl** [comment]
of course :)
